import {
  MessageCircle,
  QrCode,
  FileText,
  Mail,
  KeyRound,
} from 'lucide-react';

export const TOOLS = [
  {
    slug: 'whatsapp-link-generator',
    name: 'WhatsApp Link Generator',
    tagline: 'Create click-to-chat WhatsApp links in seconds',
    description:
      'Generate shareable WhatsApp links with pre-filled messages. Perfect for business websites, email signatures, and marketing campaigns.',
    longDescription:
      'A free WhatsApp link generator that creates wa.me click-to-chat URLs in seconds. Pick a country code, enter a phone number, and optionally add a pre-filled message — share the link anywhere and customers reach you on WhatsApp instantly. Works in 33+ countries, no account required, runs entirely in your browser.',
    seoTitle: 'Free WhatsApp Link Generator (wa.me) — Click to Chat in Seconds',
    seoDescription:
      'Generate free WhatsApp click-to-chat links (wa.me) with pre-filled messages. Works for 33+ countries. No signup, instant, private. Perfect for websites, emails & ads.',
    icon: MessageCircle,
    color: 'emerald',
    gradient: 'from-emerald-400 to-teal-400',
    tintBg: 'bg-emerald-500/15',
    tintBorder: 'border-emerald-400/30',
    tintText: 'text-emerald-300',
    tintGlow: 'shadow-[0_10px_40px_-12px_rgba(16,185,129,0.55)]',
    bgLight: 'bg-emerald-500/15',
    textColor: 'text-emerald-300',
    borderColor: 'border-emerald-400/30',
    href: '/tools/whatsapp-link-generator',
    category: 'Communication',
    badge: 'Most Popular',
    badgeVariant: 'emerald',
    keywords: [
      'whatsapp link generator',
      'click to chat whatsapp',
      'whatsapp business link',
      'wa.me link generator',
      'whatsapp url maker',
      'free whatsapp link',
    ],
    howTo: [
      { name: 'Pick country code', text: 'Select your destination country from the searchable list of 33+ countries.' },
      { name: 'Enter phone number', text: 'Type the WhatsApp number without country code, spaces, or dashes — we clean it.' },
      { name: 'Add a message (optional)', text: 'Write a pre-filled message that opens in the chat compose box.' },
      { name: 'Generate the link', text: 'Click Generate to create your wa.me click-to-chat URL.' },
      { name: 'Copy or share', text: 'Copy the link to use on your website, email signature, social bio, or QR code.' },
    ],
    faqs: [
      { q: 'What is a wa.me link?', a: 'A wa.me URL opens WhatsApp directly to a chat with a specific phone number, optionally with a pre-filled message the recipient can edit before sending.' },
      { q: 'Does it work for WhatsApp Business?', a: 'Yes — wa.me links work identically for WhatsApp and WhatsApp Business numbers.' },
      { q: 'Is the message sent automatically?', a: 'No. The message appears in the compose box; the user has full control to edit and send it.' },
    ],
  },
  {
    slug: 'qr-code-generator',
    name: 'QR Code Generator',
    tagline: 'Generate custom QR codes for any URL or text',
    description:
      'Create high-quality QR codes for websites, menus, contact info, and more. Customize colors, download as PNG.',
    longDescription:
      'A free QR code generator that creates high-resolution PNG codes for URLs, text, phone numbers, email addresses, and Wi-Fi credentials. Pick from preset colors, choose size up to 512×512, and download instantly. Print-ready for menus, posters, business cards, and product packaging.',
    seoTitle: 'Free QR Code Generator — High-Resolution PNG, Custom Colors',
    seoDescription:
      'Free QR code generator with custom colors and sizes up to 512×512 PNG. Encode URLs, Wi-Fi, contact info, text. No signup, instant download, print-ready for menus & posters.',
    icon: QrCode,
    color: 'indigo',
    gradient: 'from-indigo-400 to-violet-400',
    tintBg: 'bg-indigo-500/15',
    tintBorder: 'border-indigo-400/30',
    tintText: 'text-indigo-300',
    tintGlow: 'shadow-[0_10px_40px_-12px_rgba(99,102,241,0.6)]',
    bgLight: 'bg-indigo-500/15',
    textColor: 'text-indigo-300',
    borderColor: 'border-indigo-400/30',
    href: '/tools/qr-code-generator',
    category: 'Marketing',
    badge: 'Free Download',
    badgeVariant: 'indigo',
    keywords: [
      'qr code generator',
      'free qr code',
      'custom qr code',
      'qr code maker',
      'qr generator png',
      'wifi qr code',
    ],
    howTo: [
      { name: 'Enter your content', text: 'Paste a URL, text, email, phone number, or Wi-Fi credentials into the input.' },
      { name: 'Pick size and colors', text: 'Choose 128–512 px output and one of six color presets — or customize your own.' },
      { name: 'Set error correction', text: 'Higher correction levels survive damage, dirt, and scanning at angles.' },
      { name: 'Download PNG', text: 'Hit Download to save a print-ready PNG. Use it on menus, posters, signage, business cards.' },
    ],
    faqs: [
      { q: 'What can I encode in a QR code?', a: 'URLs, plain text, phone numbers (tel:), email (mailto:), Wi-Fi credentials, and vCard contact info — anything text-based.' },
      { q: 'Is the download free and unlimited?', a: 'Yes. Generate and download as many QR codes as you need. No watermark, no limit.' },
      { q: 'Can I customize the colors?', a: 'Yes — six preset color schemes plus full custom foreground and background pickers.' },
    ],
  },
  {
    slug: 'invoice-generator',
    name: 'Invoice Generator',
    tagline: 'Create professional invoices and print as PDF',
    description:
      'Build clean, professional invoices with line items, taxes, and totals. Print or save as PDF instantly.',
    longDescription:
      'A free invoice generator that creates clean, professional PDF invoices in your browser. Add line items, calculate taxes, support 18 currencies, and print to PDF — perfect for freelancers, contractors, and small businesses billing clients in the US, UK, EU, and beyond.',
    seoTitle: 'Free Invoice Generator — Print to PDF, 18 Currencies',
    seoDescription:
      'Create professional invoices free in your browser. 18 currencies (USD, GBP, EUR, INR, AED, SGD…), tax calculations, line items, print to PDF. No signup. Auto-saves locally.',
    icon: FileText,
    color: 'amber',
    gradient: 'from-amber-400 to-orange-400',
    tintBg: 'bg-amber-500/15',
    tintBorder: 'border-amber-400/30',
    tintText: 'text-amber-300',
    tintGlow: 'shadow-[0_10px_40px_-12px_rgba(245,158,11,0.55)]',
    bgLight: 'bg-amber-500/15',
    textColor: 'text-amber-300',
    borderColor: 'border-amber-400/30',
    href: '/tools/invoice-generator',
    category: 'Finance',
    badge: 'PDF Export',
    badgeVariant: 'amber',
    keywords: [
      'invoice generator',
      'free invoice maker',
      'online invoice generator',
      'invoice template',
      'pdf invoice',
      'freelancer invoice',
    ],
    howTo: [
      { name: 'Set invoice details', text: 'Enter invoice number, date, due date, and pick your currency.' },
      { name: 'Fill From and Bill To', text: 'Add your business details and your client\'s details.' },
      { name: 'Add line items', text: 'List each item with description, quantity, and rate. Totals calculate automatically.' },
      { name: 'Apply tax (optional)', text: 'Enter a percentage tax rate; subtotal, tax, and total show instantly.' },
      { name: 'Save as PDF', text: 'Click Print / Save as PDF — choose "Save as PDF" in your browser print dialog.' },
    ],
    faqs: [
      { q: 'Is the invoice data saved?', a: 'Yes — drafts auto-save to your browser only. Refresh and your work is still there. Nothing is sent to a server.' },
      { q: 'Which currencies are supported?', a: 'USD, GBP, EUR, INR, CAD, AUD, JPY, AED, SGD, NZD, CHF, CNY, BRL, MXN, ZAR, KRW, SEK, NOK — 18 in total.' },
      { q: 'How do I save as PDF?', a: 'Click Print, then in your browser\'s print dialog select "Save as PDF" as the destination.' },
    ],
  },
  {
    slug: 'email-signature-generator',
    name: 'Email Signature Generator',
    tagline: 'Build a polished HTML email signature',
    description:
      'Design a professional email signature with your name, title, links, and social profiles. Copy HTML instantly.',
    longDescription:
      'A free HTML email signature generator. Add your name, role, company, contact details, and social links — get a polished signature you can paste into Gmail, Outlook, Apple Mail, or Thunderbird. Five accent colors, mobile-friendly markup, and clean copyable HTML.',
    seoTitle: 'Free HTML Email Signature Generator — Gmail, Outlook, Apple Mail',
    seoDescription:
      'Build a professional HTML email signature free. Works in Gmail, Outlook, Apple Mail, Thunderbird. Add logo, social links, accent color. Copy HTML instantly. No signup.',
    icon: Mail,
    color: 'sky',
    gradient: 'from-sky-400 to-blue-400',
    tintBg: 'bg-sky-500/15',
    tintBorder: 'border-sky-400/30',
    tintText: 'text-sky-300',
    tintGlow: 'shadow-[0_10px_40px_-12px_rgba(56,189,248,0.55)]',
    bgLight: 'bg-sky-500/15',
    textColor: 'text-sky-300',
    borderColor: 'border-sky-400/30',
    href: '/tools/email-signature-generator',
    category: 'Communication',
    badge: 'Copy HTML',
    badgeVariant: 'sky',
    keywords: [
      'email signature generator',
      'html email signature',
      'professional email signature',
      'free signature maker',
      'gmail signature',
      'outlook signature',
    ],
    howTo: [
      { name: 'Fill your details', text: 'Add your name, job title, company, and contact info (email, phone, website).' },
      { name: 'Add social links', text: 'Optional: paste LinkedIn URL and Twitter/X handle to render social buttons.' },
      { name: 'Pick an accent color', text: 'Choose from five color themes that match your brand identity.' },
      { name: 'Copy the HTML', text: 'Click Copy HTML — paste into Gmail, Outlook, Apple Mail, or Thunderbird signature settings.' },
    ],
    faqs: [
      { q: 'Where do I paste the HTML?', a: 'Gmail: Settings → General → Signature → Create new → paste in source mode. Outlook: Settings → Mail → Compose and reply → Email signature.' },
      { q: 'Will it work in dark mode?', a: 'Yes — the signature uses solid colors that render correctly in both light and dark email clients.' },
      { q: 'Can I add a profile photo?', a: 'Yes — paste a public HTTPS image URL into the avatar field, or leave blank to use initials.' },
    ],
  },
  {
    slug: 'password-generator',
    name: 'Password Generator',
    tagline: 'Generate strong, secure passwords instantly',
    description:
      'Create uncrackable passwords with custom length and character sets. No data is stored or transmitted.',
    longDescription:
      'A free, cryptographically secure password generator. Built on the browser\'s crypto.getRandomValues() API — passwords never leave your device. Customize length (4–64), pick uppercase, lowercase, numbers, and symbols, and generate up to 10 passwords at once.',
    seoTitle: 'Free Strong Password Generator — Cryptographically Secure',
    seoDescription:
      'Free password generator using browser crypto APIs. 4–64 characters, custom character sets, generate up to 10 at once. 100% private — passwords never leave your device.',
    icon: KeyRound,
    color: 'rose',
    gradient: 'from-rose-400 to-fuchsia-400',
    tintBg: 'bg-rose-500/15',
    tintBorder: 'border-rose-400/30',
    tintText: 'text-rose-300',
    tintGlow: 'shadow-[0_10px_40px_-12px_rgba(244,63,94,0.55)]',
    bgLight: 'bg-rose-500/15',
    textColor: 'text-rose-300',
    borderColor: 'border-rose-400/30',
    href: '/tools/password-generator',
    category: 'Security',
    badge: '100% Private',
    badgeVariant: 'rose',
    keywords: [
      'password generator',
      'strong password generator',
      'secure password maker',
      'random password generator',
      'password creator',
      'free password tool',
    ],
    howTo: [
      { name: 'Choose length', text: 'Set password length between 4 and 64 characters. 16+ is recommended for strong security.' },
      { name: 'Pick character types', text: 'Toggle uppercase, lowercase, numbers, and symbols.' },
      { name: 'Generate passwords', text: 'Generate one or up to 10 passwords at once.' },
      { name: 'Copy and store safely', text: 'Click any password to copy it. Use a password manager to store securely.' },
    ],
    faqs: [
      { q: 'Are the passwords truly random?', a: 'Yes — generated using the browser\'s built-in crypto.getRandomValues() API, the same cryptographic primitive used in security-critical software.' },
      { q: 'Are passwords sent to a server?', a: 'Never. Generation happens 100% in your browser. We have zero visibility into what you generate.' },
      { q: 'How long should my password be?', a: 'For strong security, use 16+ characters with a mix of uppercase, lowercase, numbers, and symbols. 20+ for high-value accounts.' },
    ],
  },
];

export const TOOL_MAP = Object.fromEntries(TOOLS.map((t) => [t.slug, t]));

export const SITE = {
  name: 'PinMyBusiness',
  domain: 'pinmybusiness.com',
  url: 'https://pinmybusiness.com',
  tagline: 'Free Business Tools for Modern Entrepreneurs',
  description:
    'Free online tools for small businesses, freelancers, and creators. WhatsApp links, QR codes, invoices, email signatures, password generators — no signup required.',
  twitter: '@pinmybusiness',
  founded: '2024',
};
