// All user roles in one place
export const ROLES = {
  SUPER_ADMIN: 0,
  ADMIN: 1,
  ADMIN_TEAM: 2,
  ORGANIZATION_ADMIN: 3,
  ORGANIZATION_MANAGER: 4,
  ORGANIZATION_TEAM: 5,

  BRANCH_ADMIN: 6,
  BRANCH_MANAGER: 7,
  BRANCH_TEAM: 8,
};
